### ISSUE TITLE
Weird background behind text.

### ISSUE THREAD

**Issue by zefaxet** [sircinnamon/runescape-text#1]
I followed the example in your readme to generate the following gif:

![meme](https://user-images.githubusercontent.com/35270292/87629000-bee32380-c6f7-11ea-9c0c-cfc5310cc82a.gif)

As you can see there is an odd background behind the characters.

This was the code to produce:

```λ py
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import runescape_text as rst
>>> img = rst.parse_string("wave:glow1:Doubling bitcoin for free :) only for next 30 mins TRADE NOW !!! also buying gf")
>>> len(img)
20
>>> rst.multi_frame_save(img, file="meme.gif")
'meme.gif'
>>>
```

Thanks.

**Comment by zefaxet** [comment]
I see that the gif didnt animate so I am attaching it here.
![meme](https://user-images.githubusercontent.com/35270292/87628970-ac68ea00-c6f7-11ea-81ce-c8f2c2dbb851.gif)

**Comment by sircinnamon** [comment]
Yep, it looks like Pillow has changed something in their gif transparency code again. That will take a while to be fixed I'm sure, so in the meantime installing an older version of Pillow should fix it.

```pip install Pillow==6.0.0``` worked for me, running your same code:
![meme](https://user-images.githubusercontent.com/16858312/87677650-40a67180-c737-11ea-92cf-0064ee6d5b3c.gif)

I'll leave this issue open since the dependency issue will have to be addressed at some point.

**Comment by sircinnamon** [comment]
Looks like this issue popped up in the jump from Pillow-7.1.2 to Pillow-7.2.0. Will see if I can narrow it down to a specific commit

**Comment by sircinnamon** [comment]
Never actually figured out what changed with this, but it was happening because i was saving frames as RGBA mode and saving directly to a GIF, which apparently no longer works, as gif frames are assumed to be in P mode.

Frames are now stored in P (abad5af) and converted to RGBA when needed, and that seems to have solved this issue for me.

@zefaxet Let me know if you have any more issues!
